export enum BookErrorCodes {
  BOOK_NOT_FOUND = "BOOK_NOT_FOUND",
  BOOK_ALREADY_EXISTS = "BOOK_ALREADY_EXISTS",
  INVALID_BOOK_DATA = "INVALID_BOOK_DATA",
  DUPLICATE_ISBN = "DUPLICATE_ISBN",
  INVALID_CURSOR = "INVALID_CURSOR",
}
